/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_KEEPASSX_H
#define KEEPASSX_CONFIG_KEEPASSX_H

#define KEEPASSX_VERSION "2.3.4"

#define KEEPASSX_SOURCE_DIR "/Users/hfli/Downloads/keePassxcold"
#define KEEPASSX_BINARY_DIR "/Users/hfli/Downloads/keePassxcold"

#define KEEPASSX_PREFIX_DIR "/Applications"
#define KEEPASSX_PLUGIN_DIR "KeePassXC.app/Contents/PlugIns"
#define KEEPASSX_DATA_DIR "KeePassXC.app/Contents/Resources"

#define WITH_XC_AUTOTYPE
/* #undef WITH_XC_NETWORKING */
/* #undef WITH_XC_BROWSER */
/* #undef WITH_XC_HTTP */
/* #undef WITH_XC_YUBIKEY */
/* #undef WITH_XC_SSHAGENT */

#define KEEPASSXC_BUILD_TYPE "Release"
#define KEEPASSXC_BUILD_TYPE_RELEASE
/* #undef KEEPASSXC_BUILD_TYPE_PRE_RELEASE */
/* #undef KEEPASSXC_BUILD_TYPE_SNAPSHOT */

/* #undef KEEPASSXC_DIST */
#define KEEPASSXC_DIST_TYPE "Other"
/* #undef KEEPASSXC_DIST_SNAP */
/* #undef KEEPASSXC_DIST_APPIMAGE */

/* #undef HAVE_PR_SET_DUMPABLE */
#define HAVE_RLIMIT_CORE 1
#define HAVE_PT_DENY_ATTACH 1

#endif // KEEPASSX_CONFIG_KEEPASSX_H
